# Basic
title: ITCobber
subtitle: 上善若水，人淡如菊
welcome_message: <a href="XXXX" target="_blank">关注微信</a>
description: 学无长幼，达者为先。
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 简历, description: 团队简历, url: 'http://project.onevcat.com'}
    - {title: 关于, description: 了解更多关注我, url: 'http://example.com'}
    - {title: 更多, description: 更多, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: ITCobber
    # duoshuo:

# Social
social:
    #weibo: onevcat
    github: ITCobber
    twitter: ITCobber
    gplus: 107108267983477358170
    mail: lph_php@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
